create SERVICE & Exception packages
myj4513/command-line-project pull request #8
Opened 2021-07-05 07:51 UTC by myj4513

1. change package name [UTIL] -> [SERVICE]
2. refactor ProductService.java & userService.java
3. create Exception package & create user defined exception classes

2021-07-07 12:31 UTC, yyy9942 requested changes

2021-07-07 12:31 UTC, yyy9942 commented on src/DTO/Product.java
> +		SERVICE.ProductService.setCurrentProduct(this);
패키지명을 명시하지 않아도 ProductService를 import해서 사용할 수 있어. 그리고 ProductService 클래스를 그래도 사용하는 방법보다는 객체를 만들어서 사용하는게 더 좋아보여.

2021-07-07 12:31 UTC, yyy9942 commented on src/DTO/Product.java
> +		SERVICE.ProductService.setCurrentProduct(this);
`setCurrentProduct` 와 이 Service에 Product를 세팅하는 방식은 수정이 필요해보임

2021-07-07 12:31 UTC, yyy9942 commented on src/Exception/InvalidAmountException.java
> +    }
이러한 예외를 무조건 try-catch로 감싸야 한다면 Exception을 상속받도록 할 수 있겠지
그렇다면 try-catch나 throws 구문 없이 예외를 발생시킬 수 있는 방법은 어떤것이 있을까?

hint: Exception이 아닌 다른걸 상속하면 될거야.

2021-07-07 12:31 UTC, yyy9942 commented on src/Index.java
> +						Product cancelProduct =  SERVICE.UserService.getCurrentUser().getFundingHistory().get(UserInput.menuInput()-1);
이부분도 SERVICE. 이 아니라 UserService를 import하고, UserService 클래스가 아닌 객체를 만들어서 사용할 수 있도록 바꿔봐

2021-07-07 12:31 UTC, yyy9942 commented on src/Index.java
> +						Product cancelProduct =  SERVICE.UserService.getCurrentUser().getFundingHistory().get(UserInput.menuInput()-1);
객체를 만들어서 사용해도 static method는 사용할 수 있어

2021-07-07 12:31 UTC, yyy9942 commented on src/SERVICE/ProductService.java
> +    }
이렇게 생성자로 나에게 필요한 객체를 받아오는걸 의존성이라고 하는데, 설정 아주 잘했음!

2021-07-07 12:31 UTC, yyy9942 commented on src/SERVICE/ProductService.java
> +    }
이건 어떤 역할을 하는 메서드야? product의 currentAmount와 fundingPrice를 더해준 값을 currentAmount로 세팅해주는 기능이야?

2021-07-07 12:31 UTC, yyy9942 commented on src/UserInput.java
> +		System.out.println("\n계좌 잔액은 "+ SERVICE.UserService.getCurrentUser().getAccount()+"입니다.\n");
자바에서 패키지명은 소문자로 만드는게 일반적인 코드 컨밴션이니 변경 가능하다면 한번 바꿔봐

2021-07-08 09:36 UTC, myj4513 commented on src/DTO/Product.java
> +		SERVICE.ProductService.setCurrentProduct(this);
DTO가 Service 계층을 호출한것도 문제가 되는것 같아서 다음 PR에서 제거했습니다. 여기서 혹시 별도의 수정이 필요한가요?

2021-07-11 03:03 UTC, yyy9942 commented on src/DTO/Product.java
> +		SERVICE.ProductService.setCurrentProduct(this);
응 그렇게 하면 될거같아. Service => DAO 호출은 문제 없음. DAO => Service 호출은 안하는게 맞아

2021-07-11 03:05 UTC, closed without merging